<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="DemoTest" duration-ms="12410" started-at="2018-02-25T14:08:22Z" finished-at="2018-02-25T14:08:34Z">
    <groups>
    </groups>
    <test name="Demoxml" duration-ms="12410" started-at="2018-02-25T14:08:22Z" finished-at="2018-02-25T14:08:34Z">
      <class name="com.qa.ExtentReportListener.ExtentReportScreenshot">
        <test-method status="PASS" signature="setExtent()[pri:0, instance:com.qa.ExtentReportListener.ExtentReportScreenshot@27efef64]" name="setExtent" is-config="true" duration-ms="141" started-at="2018-02-25T19:38:22Z" finished-at="2018-02-25T19:38:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setExtent -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.qa.ExtentReportListener.ExtentReportScreenshot@27efef64]" name="setup" is-config="true" duration-ms="8863" started-at="2018-02-25T19:38:22Z" finished-at="2018-02-25T19:38:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="ExtentReportFailureScreenshot()[pri:0, instance:com.qa.ExtentReportListener.ExtentReportScreenshot@27efef64]" name="ExtentReportFailureScreenshot" duration-ms="258" started-at="2018-02-25T19:38:31Z" finished-at="2018-02-25T19:38:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Yahoo1] but found [Yahoo]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Yahoo1] but found [Yahoo]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.qa.ExtentReportListener.ExtentReportScreenshot.ExtentReportFailureScreenshot(ExtentReportScreenshot.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ExtentReportFailureScreenshot -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.ExtentReportListener.ExtentReportScreenshot@27efef64]" name="tearDown" is-config="true" duration-ms="2822" started-at="2018-02-25T19:38:31Z" finished-at="2018-02-25T19:38:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ExtentReportFailureScreenshot status=FAILURE method=ExtentReportScreenshot.ExtentReportFailureScreenshot()[pri:0, instance:com.qa.ExtentReportListener.ExtentReportScreenshot@27efef64] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:com.qa.ExtentReportListener.ExtentReportScreenshot@27efef64]" name="endReport" is-config="true" duration-ms="306" started-at="2018-02-25T19:38:34Z" finished-at="2018-02-25T19:38:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.qa.ExtentReportListener.ExtentReportScreenshot -->
    </test> <!-- Demoxml -->
  </suite> <!-- DemoTest -->
</testng-results>
